version: '3.8'

services:
  db:
    image: postgres:14
    environment:
      POSTGRES_USER: germaine
      POSTGRES_PASSWORD: govtechtkh
      POSTGRES_DB: championship_db
#    ports:
#      - "5432:5432"
    volumes:
      - postgres_data:/var/lib/postgresql/data
    networks:
      - app-network

  web:
    build: .
    environment:
      - SQLALCHEMY_DATABASE_URI=postgresql://germaine:govtechtkh@db:5432/championship_db
    ports:
      - "3000:3000"
    depends_on:
      - db
    networks:
      - app-network
    volumes:
      - .:/app

volumes:
  postgres_data:

networks:
  app-network:
